export default [
  {
    id: '1',
    name: 'van-life',
    url: 'https://inquisitive-zuccutto-886fd5.netlify.app/',
    imageSquare: '../src/assets/vanlife-square.png',
    image: '../src/assets/vanlife.png',
    type: 'react',
    github: 'https://github.com/mjlearn13/van-life.git',
  },
  {
    id: '2',
    name: 'notes-app',
    url: 'https://voluble-brioche-cf4ae0.netlify.app/',
    imageSquare: '../src/assets/notes-app-square.png',
    image: '../src/assets/notes-app.png',
    type: 'react',
    github: 'https://github.com/mjlearn13/notes-app.git',
  },
  {
    id: '3',
    name: 'pic-some',
    url: 'https://deluxe-churros-f1e05b.netlify.app/',
    imageSquare: '../src/assets/pic-some-square.png',
    image: '../src/assets/pic-some.png',
    type: 'react',
    github: 'https://github.com/mjlearn13/pic-some.git',
  },
  {
    id: '4',
    name: 'speedTypingGame',
    url: 'https://idyllic-cascaron-fc1a88.netlify.app/',
    imageSquare: '../src/assets/speedTypingGame-square.png',
    image: '../src/assets/speedTypingGame.png',
    type: 'react',
    github: 'https://github.com/mjlearn13/speedTypingGame.git',
  },
  {
    id: '5',
    name: 'tenzies',
    url: 'https://fastidious-chaja-ae6f30.netlify.app/',
    imageSquare: '../src/assets/tenzies-square.png',
    image: '../src/assets/tenzies.png',
    type: 'react',
    github: 'https://github.com/mjlearn13/tenzies.git',
  },
]